Add cpp template
OpenRHINO/RHINO-CLI pull request #17
Opened 2023-02-04 15:04 UTC by chichi321

2023-02-06 01:49 UTC, zpltys reviewed
代码里可以实现一个简单的mpi hello world，方便别人使用以及自己的测试

2023-02-06 02:50 UTC, zpltys approved these changes

2023-02-06 05:51 UTC, LI-Mingyu commented
经电话沟通， 朱赫（ @chichi321 ） 会单独写一个sample，放到sample文件夹下，配合这里修改后的template。写完后和这里的template合为一个PR提交。

2023-02-07 11:52 UTC, LI-Mingyu requested changes
基于这个模板的samples/integration，用 rhino cli build 出来的镜像，不能正常运行
launch pod日志如下：
<img width="719" alt="image" src="https://user-images.githubusercontent.com/20229719/217237644-fb68cef0-dbb6-4d93-bc2d-d7810114ba07.png">

2023-02-09 06:20 UTC, TimeSea05 commented
用rhino create的时候会有一个lang的选项，比如c, cpp，按理说lang为c的时候，下载下来的应该是一个c文件的模板，但是现在下载下来是一个cpp文件的模板。所以我觉得应该在template仓库里面多加一个zip，把c和cpp分开

2023-02-09 08:04 UTC, TimeSea05 approved these changes

2023-02-09 08:28 UTC, LI-Mingyu approved these changes

2023-02-09 08:29 UTC, merged